//! Arithmetic over GF(256), the finite field used by QR Reed-Solomon error
//! correction. The field is GF(2^8) generated by the primitive polynomial
//! 0x11D (x^8 + x^4 + x^3 + x^2 + 1) with generator element alpha = 2.
//!
//! Both lookup tables are generated at comptime (memory-model + comptime idioms
//! from the wiki: build static tables with a `comptime`/`blk:` loop, no runtime
//! initialization). `exp[i] = alpha^i` and `log[exp[i]] = i`. The multiplicative
//! group has order 255, so exponents are taken mod 255.

const std = @import("std");

/// Primitive polynomial for QR codes (bit 8 set is folded back in).
pub const primitive: u16 = 0x11D;

/// exp[i] = alpha^i in GF(256). exp[255] wraps back to exp[0] == 1.
pub const exp_table: [256]u8 = blk: {
    @setEvalBranchQuota(10_000);
    var table: [256]u8 = undefined;
    var x: u16 = 1;
    var i: usize = 0;
    while (i < 256) : (i += 1) {
        table[i] = @intCast(x & 0xFF);
        x <<= 1;
        if (x & 0x100 != 0) x ^= primitive;
    }
    break :blk table;
};

/// log[v] = the exponent i such that alpha^i == v, for v in 1..=255.
/// log[0] is undefined mathematically; we store 0 as a sentinel and callers
/// must guard against zero operands (see `mul`/`div`).
pub const log_table: [256]u8 = blk: {
    @setEvalBranchQuota(10_000);
    var table: [256]u8 = [_]u8{0} ** 256;
    var i: usize = 0;
    // i goes 0..254 so log[1] stays 0 (exp[255] also == 1, but we skip it).
    while (i < 255) : (i += 1) {
        table[exp_table[i]] = @intCast(i);
    }
    break :blk table;
};

/// Multiply two field elements. Returns 0 if either operand is 0.
pub fn mul(a: u8, b: u8) u8 {
    if (a == 0 or b == 0) return 0;
    const log_sum = @as(u16, log_table[a]) + @as(u16, log_table[b]);
    return exp_table[log_sum % 255];
}

/// Divide a by b in the field. Asserts b != 0. Returns 0 when a == 0.
pub fn div(a: u8, b: u8) u8 {
    std.debug.assert(b != 0);
    if (a == 0) return 0;
    const log_diff = @as(i16, log_table[a]) - @as(i16, log_table[b]) + 255;
    return exp_table[@as(usize, @intCast(log_diff)) % 255];
}

/// alpha raised to an arbitrary (possibly large) exponent.
pub fn expOf(power: usize) u8 {
    return exp_table[power % 255];
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test "exp/log are inverses" {
    // log(exp(i)) == i for every exponent in the multiplicative group.
    var i: usize = 0;
    while (i < 255) : (i += 1) {
        try std.testing.expectEqual(@as(u8, @intCast(i)), log_table[exp_table[i]]);
    }
    // exp(log(v)) == v for every nonzero element.
    var v: u16 = 1;
    while (v < 256) : (v += 1) {
        const e: u8 = @intCast(v);
        try std.testing.expectEqual(e, exp_table[log_table[e]]);
    }
}

test "field generator wraps with period 255" {
    try std.testing.expectEqual(@as(u8, 1), exp_table[0]);
    try std.testing.expectEqual(@as(u8, 2), exp_table[1]);
    try std.testing.expectEqual(@as(u8, 1), exp_table[255]);
}

test "mul identities and zero absorption" {
    try std.testing.expectEqual(@as(u8, 0), mul(0, 123));
    try std.testing.expectEqual(@as(u8, 0), mul(123, 0));
    var v: u16 = 0;
    while (v < 256) : (v += 1) {
        const e: u8 = @intCast(v);
        try std.testing.expectEqual(e, mul(1, e)); // 1 is multiplicative identity
        try std.testing.expectEqual(mul(e, 7), mul(7, e)); // commutative
    }
}

test "div inverts mul" {
    var a: u16 = 1;
    while (a < 256) : (a += 1) {
        var b: u16 = 1;
        while (b < 256) : (b += 1) {
            const ea: u8 = @intCast(a);
            const eb: u8 = @intCast(b);
            const product = mul(ea, eb);
            try std.testing.expectEqual(ea, div(product, eb));
        }
    }
}
